# Generated by Django 5.0.2 on 2024-03-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='refreshed_token',
            new_name='refresh_token',
        ),
    ]
